title: Hotelling Model and the Green Paradox

stories:
  GreenParadox_quiz:


descr: |
  Author: [Sebastian Kranz, Ulm University](https://www.uni-ulm.de/mawi/mawi-wiwi/mitarbeiter/skranz.html)
  
  The model first allows some interactive simulations of a simple Hotelling model
  for the extraction of fossil fuels. One can study and is quizzed on the effects 
  of the interest rate on the path of fossil fuel extraction which is tightly
  linked to the path of CO2 emmissions.

  Then the effects of climate treaties in which parts of the world participate
  are studied. 
  If treaty states reduce their demand, world-wide fossil fuel prices go down, 
  and as a reaction non-treaty states tend to burn more fossil fuels.
  The simulations illustrate this "Carbon-Leakage" effect.
  It is illustrated how climate treaties that comprehend only a medium fraction of the
  world's countries can be much less effective than treates with a world-wide coverage.

  Finally, the model can illustrate the so called "Green Paradox", a termed coined
  by the German economist Hands-Werner Sinn. A treaty that prescribes a gradual
  decline of CO2 emmission or which takes time to be in place, can lead to an
  increase of current CO2 emmssions, since ressource owners anticipate that reduced
  future demand makes their ressource less valuable. In effect, such a treaty may
  (but not neccessarily does) paradoxically lead to a less desirable path of CO2
  emmissions than in the absence of any treaty.

  
footnotes:
  Anmerkungen:
    title: Remarks
    descr: >
    	So far no attempt at all is made to calibrate the
    	simple model to any data. The simulations shall
    	just illustrate some effect if we take the dynamic
    	optimization considerations of suppliers of 
    	fossil fuels into account.